server:
  port: 7320
spring:
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://med-user
          predicates:
            - Path=/users/**,/doctors/**
        - id: appointment
          uri: lb://med-appointment
          predicates:
            - Path=/appointment/**,/department/**,/schedule/**
        - id: consult
          uri: lb://med-consult
          predicates:
            - Path=/consult/**
        - id: prescription
          uri: lb://med-prescription
          predicates:
            - Path=/prescription/**,/drug/**
        - id: payment
          uri: lb://med-pay
          predicates:
            - Path=/pay/**
hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /users/login
      - /doctors/register
      - /doctors/login
      - /users/register
      - /department
      - /schedule/**
    rolePaths:
      admin:
        - /**
      doctor:
        - /**
      user:
        - /appointment/u/**
        - /pay/**
        - /users/**

