server:
  port: 7320
spring:
  cloud:
    gateway:
      routes:
        - id: appointment
          uri: lb://med-appointment
          predicates:
            - Path=/appointment/**
            - Path=/department/**
        - id: consult
          uri: lb://med-consult
          predicates:
            - Path=/consult/**
        - id: user
          uri: lb://med-user
          predicates:
            - Path=/users/**
        - id: prescription
          uri: lb://med-prescription
          predicates:
            - Path=/prescription/**
            - Path=/drug/**
hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /users/login
      - /users/register